apiVersion: batch/v1
kind: Job
metadata:
  name: copy-content-job
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Hello, World!' > /mnt/nfs/index.html"]
        volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs
      restartPolicy: OnFailure
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
